### ISSUE TITLE
AFP-REPLACE Usage

### ISSUE THREAD

**Issue by timyounes** [audreyt/openafp-utils#6]
Hi,

What is the usage of AFP-REPLACE module? Do you have any example of map.txt?

**Comment by audreyt** [comment]
In https://github.com/audreyt/openafp-utils/blob/master/afp-replace.hs#L82 and https://github.com/audreyt/openafp-utils/blob/master/afp-replace.hs#L70 there is an implicit assumption of Big5 character set (MBCS, 0xA140 = U+3000).

Maps should be like:

```
FROM1
TO1
--
--
FROM2
TO2
```

**Comment by timyounes** [comment]
Hi @audreyt,

Can you specify example map file? I can understand your example.

Thanks

**Comment by audreyt** [comment]
Each pair of lines determines what to search for and what to replace with.

Sorry for the lack of details / examples — I searched a bit but it's been years since I developed this utility, and I don't have example files with me anymore.

(My current day job as Digital Minister @ Taiwan also makes it more difficult to respond in a timely fashion, so apologies in advance for lack of support.)

**Comment by timyounes** [comment]
So it is possible to replace afp content?

**Comment by timyounes** [comment]
Hi @audreyt,

What type of AFP content that AFP-REPLACE can replace? It can replace images and text inside AFP file?

**Comment by audreyt** [comment]
It only replaces `PTX TRN` records and does not handle other records (including images).

**Comment by timyounes** [comment]
How about TLE values?

**Comment by audreyt** [comment]
Not at the moment.

**Comment by timyounes** [comment]
Thanks @audreyt
